app/delivery/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired
from wtforms import FileField, StringField, SubmitField
from wtforms.validators import DataRequired, Email


class FileForm(FlaskForm):
    file = FileField('Filename', validators=[FileRequired()])
    email_recipient = StringField('E-Mail Recipient', validators=[DataRequired(), Email()])
    submit = SubmitField('Deliver')

app/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired
from wtforms import SubmitField, StringField, PasswordField, BooleanField, FileField
from wtforms.validators import DataRequired, Email


class LoginForm(FlaskForm):
    # TODO dynamically provide EN or DE labels
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class FileForm(FlaskForm):
    # TODO dynamically provide EN or DE labels
    file = FileField('Filename', validators=[FileRequired()])
    email_recipient = StringField('E-Mail Recipient', validators=[DataRequired()])
    submit = SubmitField('Deliver')


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('E-Mail', validators=[DataRequired(), Email()])
    submit = SubmitField('Register')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from werkzeug.exceptions import RequestEntityTooLarge

from config import config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
mail = Mail()
bootstrap = Bootstrap()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)

    from .auth import blueprint as auth_blueprint
    from .delivery import blueprint as delivery_blueprint
    from .landing import blueprint as landing_blueprint

    @delivery_blueprint.app_errorhandler(500)
    def internal_server_error(e):
        return render_template('500.html'), 500

    @delivery_blueprint.app_errorhandler(413)
    @delivery_blueprint.app_errorhandler(RequestEntityTooLarge)
    def request_entity_too_large(e):
        return render_template('413.html'), 413

    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(delivery_blueprint, url_prefix='/delivery')
    app.register_blueprint(landing_blueprint, url_prefix='/')

    return app

app/delivery/__init__.py
from flask import Blueprint

blueprint = Blueprint('delivery', __name__)

from . import forms, views

app/delivery/views.py
from io import BytesIO

from PyPDF2 import PdfFileWriter
from flask import render_template, url_for, flash
from flask_login import login_required
from werkzeug.utils import secure_filename, redirect

from app.delivery.forms import FileForm
from app.emails import send_mail
from app.security import get_password
from config import Config
from . import blueprint
from ..pdfhelper import provide_pdf_file_reader


@blueprint.route('/send-mail', methods=['GET', 'POST'])
@login_required
def delivery():
    file_form = FileForm()
    if file_form.validate_on_submit():

        reader, is_ok = provide_pdf_file_reader(BytesIO(file_form.file.data.read()))

        if not is_ok:
            flash('Invalid pdf file provided.')
            return render_template('delivery.html', form=file_form)

        out = PdfFileWriter()

        for page in range(reader.numPages):
            out.addPage(reader.getPage(page))

        password = get_password()
        filename = secure_filename(str(file_form.file.data.filename).strip())

        out.encrypt(password)

        attachment = BytesIO()

        out.write(attachment)

        email_recipient = str(file_form.email_recipient.data).strip()

        send_mail('Attachment',
                  Config.ADMINS[0],
                  [email_recipient],
                  'Zustellung von ' + filename,
                  filename,
                  attachment.getvalue())

        send_mail('Password',
                  Config.ADMINS[0],
                  [email_recipient],
                  password, None, None)

        flash('Successfully delivered ' + filename + ' to ' + email_recipient + '.')

        return redirect(url_for('.delivery'))

    if len(file_form.errors) > 0:
        for error in file_form.errors.values():
            flash(str(error))

    return render_template('delivery.html', form=file_form)

app/landing/__init__.py
from flask import Blueprint

blueprint = Blueprint('landing', __name__)

from . import views

app/landing/views.py
from . import blueprint

from flask import render_template, url_for


@blueprint.route('/')
@blueprint.route('/index')
def index():
    return render_template('index.html')

app/templates/413.html
{% extends "base.html" %}
{% block app_content %}
<h3>File size is too large.</h3>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('landing.index') }}">Start</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('auth.login') }}">Anmelden</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Abmelden</a></li>
                    <li><a href="{{ url_for('auth.register') }}">Registration</a></li>
                    <li><a href="{{ url_for('delivery.delivery') }}">Zustellung</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/delivery.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <h1>File Delivery</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
<div xmlns="http://www.w3.org/1999/html">
    <p>
        Willkommen zu dem kleinen Projekt <em>Verschlüsselter Anhang</em>.
    </p>
    <p>
        Mit diesem Webservice lassen sich pdf-Dateien als E-Mail Anhang verschicken, die mittels <a href="https://pypi.org/project/PyPDF2/">PyPDF2</a> verschlüsselt werden.</br>
        Der/die Empfänger/in erhält von der E-Mail Adresse <tt>zustellung@verschluesselter-anhang.de</tt> zwei E-Mails: Eine E-Mail mit der verschlüsselten pdf-Datei als Anhang und eine weitere E-Mail mit dem Passwort.</br>
        Zu beachten ist, dass die pdf-Datei gänzlich verschlüsselt ist, d.h. um sie wiederkehrend zu lesen, muss erneut das Passwort eingegeben werden, sofern der verwendete pdf Reader dieses nicht speichert oder die Möglichkeit bietet die pdf-Datei final zu entschlüsseln.
    </p>
    <p>
        Der Webservice ist in <a href="https://flask.palletsprojects.com/en/2.0.x/">Python (Flask)</a> geschrieben und läuft bei <a href="https://uberspace.de/de/">Uberspace</a>. Von registrierten Benutzer/innen werden lediglich deren Benutzernamen und Passwort gespeichert. Die E-Mails werden mittels <a href="https://www.ionos.de/office-loesungen/eigene-email-adresse">IONOS</a> verschickt.
    </p>
    <p>
        Der Quellcode ist auf <a href="https://github.com/patient-developer/secure-delivery">Github</a> zu finden.
    </p>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
  <h1>Sign In</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <h1>Register</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}